[workspace]
members = [
    'runtime',
    'node/parachain',
    'client/rpc/txpool',
    'client/rpc-core/txpool',
    # We do NOT include the standalone node in this main workspace because it builds the
    # runtime with the `standalone` feature, which the parachain does not support.
]

[profile.release]
panic = 'unwind'
