[package]
name = "orml-oracle-rpc-runtime-api"
version = "0.3.2-dev"
authors = ["Laminar Developers <hello@laminar.one>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false, features = ["derive"] }
sp-api = { default-features = false, version = "2.0.0" }
sp-std = { default-features = false, version = "2.0.0" }

[features]
default = ["std"]
std = [
	"codec/std",
	"sp-api/std",
	"sp-std/std"
]
