[package]
name = "shadows-rpc-txpool"
version = '0.1.0'
authors = ['ShadowsNetwork']
edition = '2018'
homepage = 'https://shadows.network'
license = 'GPL-3.0-only'
repository = 'https://github.com/ShadowsNetwork/shadows/'

[dependencies]
sha3 = "0.8"
jsonrpc-core = "15.0.0"
ethereum-types = "0.10.0"
ethereum = { git = "https://github.com/rust-blockchain/ethereum", branch = "master", features = ["with-codec"] }
shadows-rpc-core-txpool = { path = "../../rpc-core/txpool" }
sp-runtime = { git = "https://github.com/paritytech/substrate.git", branch = "master" }
sp-api = { git = "https://github.com/paritytech/substrate.git", branch = "master" }
sp-io = { git = "https://github.com/paritytech/substrate.git", branch = "master" }
sp-std = { git = "https://github.com/paritytech/substrate.git", branch = "master" }
sp-blockchain = { git = "https://github.com/paritytech/substrate.git", branch = "master" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate.git", branch = "master" }
frame-system = { git = "https://github.com/paritytech/substrate.git", branch = "master" }
serde = { version = "1.0", features = ["derive"] }

shadows-rpc-primitives-txpool = { path = "../../../primitives/rpc/txpool" }
