[package]
name = "stake"
version = "0.1.1"
authors = ["ShadowsNetwork"]
edition = "2018"
description = "staking pallet for validator selection and rewards"

[dependencies]
author-inherent = { path = "../author-inherent", default-features = false }
frame-support = { git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
pallet-balances = { git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
pallet-staking = { git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
parity-scale-codec = { version = "1.0.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.101", optional = true }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }

[dev-dependencies]
sp-io = { git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }

[features]
default = ["std"]
std = [
	"author-inherent/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-balances/std",
	"pallet-staking/std",
	"parity-scale-codec/std",
	"serde/std",
	"sp-std/std",
	"sp-runtime/std",
]
